## redirect output from each thread
/control/cout/setCoutFile leap.out
/control/cout/setCerrFile leap.err

## Verbosity
/control/verbose 0
/process/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/run/printProgress 100000

## Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 1

## Overlap Checking
/user/det/setOverlapChecking false

## Physics
/user/phy/setPhysics Option0
#/user/phy/setPhysics Option1
#/user/phy/setPhysics Option2


## Initialize kernel
/run/initialize

## Source Particle
/gps/particle gamma
/gps/ene/mono 100. keV

## Source Geometry
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 50.0 cm
/gps/pos/halfy 50.0 cm
/gps/pos/centre 0. 0. 200. cm

# RANDOM NUMBER
#
/random/setSeeds 101 101

## Change file name
/analysis/setFileName ../data/test1.csv


## Start run
/run/beamOn 500

